window.DashCharts = (() => {
  const charts={};
  const colors={green:'#18864b',green2:'#61b67e',navy:'#242342',amber:'#c78308',red:'#c83c3c',gray:'#a2a1ae'};
  function make(id,config){ if(charts[id]) charts[id].destroy(); const el=document.getElementById(id); if(!el)return; charts[id]=new Chart(el,config); }
  const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}};
  function evolution(rows){ const r=[...rows].sort((a,b)=>Number(a.ano)-Number(b.ano)); make('chartEvolucao',{type:'line',data:{labels:r.map(x=>x.ano),datasets:[{label:'Média',data:r.map(x=>x.media_geral??x.media),borderColor:colors.navy,backgroundColor:'#24234218',fill:true,tension:.25,yAxisID:'y'},{label:'Frequência',data:r.map(x=>x.frequencia_media??x.frequencia_percentual),borderColor:colors.green,tension:.25,yAxisID:'y1'}]},options:{...base,scales:{y:{min:0,max:10},y1:{min:0,max:100,position:'right',grid:{drawOnChartArea:false}}}}}); }
  function doughnut(id,labels,values,palette,onClick){ make(id,{type:'doughnut',data:{labels,datasets:[{data:values,backgroundColor:palette,borderColor:'#fff',borderWidth:2}]},options:{...base,cutout:'62%',onClick:(_,els)=>{if(els.length&&onClick)onClick(labels[els[0].index]);}}}); }
  function vinculos(alunos){ const map={Ativos:0,Formandos:0,Egressos:0,Inativos:0,'Evasão provável':0,'Sem dados':0}; alunos.forEach(a=>{const g=DashFilters.statusGroup(a); const k={ativo:'Ativos',formando:'Formandos',egresso:'Egressos',inativo:'Inativos',evasao:'Evasão provável',sem_dados:'Sem dados'}[g]; map[k]++;}); doughnut('chartVinculos',Object.keys(map),Object.values(map),[colors.green,colors.green2,colors.navy,colors.amber,colors.red,colors.gray],l=>document.dispatchEvent(new CustomEvent('dash:vinculo',{detail:l}))); }
  function desempenho(alunos){ const order=['Destaque','Regular','Atenção','Crítico','Sem dados']; const values=order.map(k=>alunos.filter(a=>DashFilters.norm(DashFilters.currentClass(a))===DashFilters.norm(k)).length); doughnut('chartDesempenho',order,values,[colors.green,colors.navy,colors.amber,colors.red,colors.gray],l=>document.dispatchEvent(new CustomEvent('dash:desempenho',{detail:l}))); }
  function bars(id,rows,labelKey,valueKey,color=colors.red){ make(id,{type:'bar',data:{labels:rows.map(x=>x[labelKey]),datasets:[{label:'Média',data:rows.map(x=>x[valueKey]),backgroundColor:color,borderRadius:5}]},options:{...base,indexAxis:'y',scales:{x:{beginAtZero:true,max:10}},plugins:{...base.plugins,legend:{display:false}}}}); }
  function student(rows){ const r=[...rows].sort((a,b)=>Number(a.ano)-Number(b.ano)); make('chartAluno',{type:'line',data:{labels:r.map(x=>x.ano),datasets:[{label:'Média anual',data:r.map(x=>x.media_geral??x.media_historica??x.media),borderColor:colors.navy,tension:.25},{label:'Frequência',data:r.map(x=>x.frequencia_media??x.frequencia_percentual),borderColor:colors.green,tension:.25,yAxisID:'y1'}]},options:{...base,scales:{y:{min:0,max:10},y1:{min:0,max:100,position:'right',grid:{drawOnChartArea:false}}}}}); }
  return {evolution,vinculos,desempenho,bars,student};
})();
